apiVersion: v1
baseDomain: sterling.xyz
metadata:
  name: workcluster
compute:
  - name: worker
    replicas: 2
controlPlane:
  name: master
  replicas: 3
networking:
  machineNetwork:
  - cidr: 10.151.87.0/24
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
    mtu: 8900  
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIPs: 
      - 10.151.87.99
    ingressVIPs: 
      - 10.151.87.100
pullSecret: 'your pull sevret here'
sshKey: 'public key here'



